### ISSUE TITLE
nodir broke from 4.3.5 -> 4.5.0

### ISSUE THREAD

**Issue by nikku** [isaacs/node-glob#174] opened 2015-03-07 20:53 UTC
Given the following directory structure:

```
posts
 ├── a.md
 ├── b.md
 ├── c.md
 └── folder
```

`glob('*/*', { nodir: true })` returned `[ a.md, b.md, c.md ]` in 4.3.5. The same expression includes the folder in 4.5.0.

**Comment by schnittstabil** [comment] 2015-03-07 20:59
Works in 4.4.0 as expected, but fails also in 5.0.0 :-(

**Comment by schnittstabil** [comment] 2015-03-07 21:05
@nikku I can't reproduce your test with the async call - It seems to me, that it's only a `glob.sync` issue.

**Comment by isaacs** [comment] 2015-03-07 21:58
Looks like this is a regression in the `cwd` handling.  @nikku, I can't reproduce your test case without setting a `cwd` option, and only in sync mode, is that what you're seeing as well?

```
$ tree test
test
└── posts/
    ├── folder/
    ├── a.md
    ├── b.md
    └── c.md

2 directories, 3 files
$ cd test

$ node -e 'require("glob")("**/*", {cwd:"test",nodir:true}, console.log)'
null []

$ node -e 'require("glob")("**/*", {nodir:true}, console.log)'null [ 'posts/a.md', 'posts/b.md', 'posts/c.md' ]

$ node -p 'require("glob").sync("**/*", {nodir:true})'
[ 'posts/a.md', 'posts/b.md', 'posts/c.md' ]

$ cd ..

$ node -e 'require("glob")("**/*", {cwd:"test",nodir:true}, console.log)'
null [ 'posts/a.md', 'posts/b.md', 'posts/c.md' ]

$ node -p 'require("glob").sync("**/*", {cwd:"test",nodir:true})'[ 'posts',
  'posts/a.md',
  'posts/b.md',
  'posts/c.md',
  'posts/folder' ]
```

Will investigate and publish a 4.5.1 and 5.0.1 with the fix.

**Comment by isaacs** [comment] 2015-03-07 22:01
Same with non-globstar as well:

```
$ cd test

$ node -e 'require("glob")("*/*", {nodir:true}, console.log)'
null [ 'posts/a.md', 'posts/b.md', 'posts/c.md' ]

$ node -p 'require("glob").sync("*/*", {nodir:true})'
[ 'posts/a.md', 'posts/b.md', 'posts/c.md' ]

$ cd ..

$ node -e 'require("glob")("*/*", {cwd:"test",nodir:true}, console.log)'
null [ 'posts/a.md', 'posts/b.md', 'posts/c.md' ]

$ node -p 'require("glob").sync("*/*", {cwd:"test",nodir:true})'
[ 'posts/a.md', 'posts/b.md', 'posts/c.md', 'posts/folder' ]
```

**Comment by nikku** [comment] 2015-03-07 22:32
Yes, sorry for the sloppy bug report. I am using sync + cwd, too.

**Comment by isaacs** [comment] 2015-03-07 22:54
No problem at all, @nikku.  Thanks for confirming.

Fixed on 4.5.1 and 5.0.1.

**Closed** 2015-03-07 22:53 UTC

**Comment by schnittstabil** [comment] 2015-03-07 22:56
Wow, that was fast! Thanks a lot!

**Comment by dzire187** [comment] 2015-06-19 16:06
We're still running into this issue when using options "cwd" and "nodir".
node-glob: 5.0.10
Windows: 10.0.10.130

**Comment by isaacs** [comment] 2015-06-19 17:27
@dzire187 Can you clarify exactly what you mean by "this issue"?  Are you using exactly the same pattern and folder structure as presented in the original post, or do you have a different test case that is failing in a similar way?
