### ISSUE TITLE
Issue with UNC paths on Windows

### ISSUE THREAD

**Issue by gotdibbs** [isaacs/node-glob#74] opened 2013-09-23 18:56 UTC
When a UNC path is provided as part of the pattern to match, it is incorrectly transformed to an invalid path on the local computer.

e.x. `\\nas\node\` incorrectly becomes `/nas/node` which is treated as `C:\nas\node\`.

**Comment by jdoles** [comment] 2015-01-14 12:02
+1 as well.
It would be a huge help to be able to use UNC paths in Windows.

**Comment by Mellbourn** [comment] 2015-01-29 15:23
+1

**Comment by Tineler** [comment] 2015-01-30 12:57
+1

**Comment by mark-zacharias** [comment] 2015-02-04 23:54
+1

**Comment by chrischain** [comment] 2015-02-11 19:24
+1

**Comment by contra** [comment] 2015-02-11 19:49
When people +1 things it usually delays it even more. Please don't be that person.

**Comment by stefanpenner** [comment] 2015-04-24 16:57
Ah, just ran into this one as well. I can confirm that @staticshock's fix appears to work.

@isaacs just a friendly reminder in-case this one has falling off your radar.

**Comment by isaacs** [comment] 2015-04-24 18:04
@stefanpenner et al: See #146. I need a test that passes with the patch, and *doesn't* pass without the patch.

Nothing can be landed in this library with a valid test.  I'm sorry for being so strict about this, but it's the only thing that makes maintenance of this module even remotely possible.

**Comment by stefanpenner** [comment] 2015-04-24 18:17
> Nothing can be landed in this library with a valid test. I'm sorry for being so strict about this, but it's the only thing that makes maintenance of this module even remotely possible.

I absolutely agree, good coverage is paramount.

I was sending the ping, not to merge, but to make sure you had not forgotten the issue in the first place. As there may have been a small chance you have time to address your own concerns. I suspect based on the comment you do not.

Although I have a work-around, I would prefer to not have to play wack-a-mole going forward. So let me see if I can nail down that test case for you this afternoon.

**Comment by staticshock** [comment] 2015-04-24 18:21
I've already submitted a test case that works on Windows, and haven't really had any time to look at it since then. So if you tackle this, make sure your approach meets @isaacs's "must run on linux" criterion.

**Comment by stefanpenner** [comment] 2015-04-24 18:34
@isaacs ah, it seems like this library should actually be run on a windows CI as well. What are your thoughts on this? I will gladly do the work to make it run on appveyor.

**Comment by isaacs** [comment] 2015-04-24 20:15
Yes, the test needs to run on Unix (mostly so I don't inadvertently destroy it some day, which I probably will otherwise).

Windows CI would be awesome, and I'd greatly appreciate getting this module running somewhere.  But it's not a replacement for a test that runs on Unix.

**Comment by stefanpenner** [comment] 2015-04-24 21:26
> Windows CI would be awesome, and I'd greatly appreciate getting this module running somewhere. But it's not a replacement for a test that runs on Unix.

proposed resolution:

* get this project working running / testing on appveyor
* ensure @staticshock's scenario is also testable in some way on nix

**Comment by isaacs** [comment] 2015-04-24 21:33
Yes, plus one, would merge.  I suggest hijacking or mocking whatever is necessary to make the patch in #146 testable on unix.  That's actually all that's missing from getting to UNC support; appveyor is optional.

**Comment by stefanpenner** [comment] 2015-04-24 21:42
> Yes, plus one, would merge. I suggest hijacking or mocking whatever is necessary to make the patch in #146 testable on unix. That's actually all that's missing from getting to UNC support; appveyor is optional.

Alright, I will look into this later this afternoon. I refuse to play wack-a-mole, so I am down for doing the leg work to @staticshock's fix in.

**Comment by QbProg** [comment] 2015-11-11 13:07
When this will be merged? I'm using 5.0.15 and still have this issue

**Comment by gercheq** [comment] 2015-11-12 18:14
Hi! I'm waiting for a fix as well. Could you please kindly let me know when this fix will be merged? Thanks!

**Comment by isaacs** [comment] 2015-11-12 19:29
There isn't a working fix to merge, or else I would have done so by now.  What you're waiting for is not "this fix to land", but rather "a fix to exist".

Here's what's needed for a valid solution, to this or any defect in any code I maintain:

1. Code that fixes the problem.
2. Tests that fail without the patch, and pass with the patch.
3. Those tests have to run on Unix systems (mock everything, I don't care, but the test has to actually run)

Without (2), it's not clear that the code actually works.  Without (3), the tests will start failing some day and no one will notice.  These aren't weird desert island requirements or unrealistic doom and gloom predictions.  They're just what happens.

I haven't had time to dig into this particular issue.  @stefanpenner made a courageous attempt, but then seems to have faded away with an ominous last message about a Pandora's Box.

I understand that this is important to you all.  That importance does not change the fact that I cannot accept changes that are going to reduce test quality.  Maybe if one of you work at a company that benefits from having a glob implementation in JavaScript, and is affected by this Windows-specific issue, you can try to convince your boss to let you spend a few days working on it.

**Comment by QbProg** [comment] 2015-11-13 13:10
@isaacs thank you for the explanation, I totally agree with your criteria. 
In case I find some free time to implement a fix, I see a difficulty in writing the tests since unc paths are relative to a local network resource which of course will not be available for other users. 
Do you have any suggestion? 
Test could be written for the parser part of course...

**Comment by stefanpenner** [comment] 2015-11-13 16:24
> I haven't had time to dig into this particular issue. @stefanpenner made a courageous attempt, but then seems to have faded away with an ominous last message about a Pandora's Box.

I also forgot about it after a vacation. Adding it to my calendar, will revive this weekend.

**Comment by stefanpenner** [comment] 2015-11-13 16:29
If memory serves a mixture of UNC and `cwd` was the pandoras box I noticed. Basically if `cwd` was a UNC path, fun things would happen.

My PR (although some more massaging needed)  even without the `cwd` support, would be a really good step in the correct direction. Fixing all the scenarios I could come across, except if a user changed the `cwd` to a UNC path. I suspect the `cwd` stuff could also be tackled, but maybe at a later time.

@isaacs would you be alright with improved UNC support being merged, but leaving some scenarios related to `cwd` also being on a UNC path for a future PR ?

**Comment by cmawhorter** [comment] 2016-02-23 00:01
has anyone explored require('path').normalize?  from looking at the path.js source it looks like a lot of cross-platform work has been done and it supports UNC.  i'm doing `glob() { if (IS_WIN) path.normalize }` in my workaround to fix my specific issue.

and there is [cygwin paths](https://cygwin.com/cygwin-ug-net/cygpath.html) which might be worth exploring?

**Comment by riteshatsencha** [comment] 2016-12-12 18:38
Any updates on this issue? Facing the same issue. Thx.

**Comment by designerx2** [comment] 2016-12-20 22:53
Another user stung by the UNC issue. I'm not following the potential work arounds mentioned above. Any assistance is greatly appreciated. Thank you.

**Comment by michaeldewayneharris** [comment] 2017-06-06 20:07
Any updates on this issue? Facing the same issue. Thx.

**Comment by michaeldewayneharris** [comment] 2017-06-06 20:26
I can verify that staticshock's fix works.  Until this gets merged in you can get around it by replacing your node_modules\glob\common.js with contents of https://raw.githubusercontent.com/staticshock/node-glob/023f870c210f7f59a322582c719b21e2ec357d44/common.js.  It's a shame windows fix is being held up by UNIX requirements, for years.

**Comment by Nepoxx** [comment] 2017-08-14 13:53
Is this "simply" a case of passing the right path to the OS or is it more complicated in that you need some NFS specific code for node's `fs`?

**Comment by mpaland** [comment] 2017-11-17 17:47
Late to this party... Having this issue on a Win10 node trying to access/scan a NAS like '\\host\my_media\**\*'.
@isaacs @stefanpenner Is there a mergable PR to fix this long standing UNC issue on Windows?
Would be very appreciated!

**Comment by pste** [comment] 2018-03-02 08:54
@mpaland The party's not over :)
No needed to fix, use the **cwd** parameter:
`glob("**/*.pdf", {cwd:"//host/my_media"}, (err, files) => { if (err) throw err; console.log(files) });`

**Comment by khullah** [comment] 2018-04-10 17:40
@pste solution works with Windows drive letters as well ( `{cwd:"C:"}` )

**Comment by ray007** [comment] 2019-02-28 13:39
I'm not using `glob` directly but through `gulp.src()`, and setting the `cwd` option there does not seem to help.

Not really familiar with the code, but after a quick look, could the problem be in the `minimatch` module?

**Comment by ray007** [comment] 2019-03-08 12:25
Not sure what I did wrong last week, but the `cwd` option did just make things work.
Back to the original issue, because `gulp.src()` still fails.

**Comment by sangimed** [comment] 2020-04-08 21:09
> 
> 
> @mpaland The party's not over :)
> No needed to fix, use the **cwd** parameter:
> `glob("**/*.pdf", {cwd:"//host/my_media"}, (err, files) => { if (err) throw err; console.log(files) });`

Tried this in Windows Server 2012 R2 but didn't work (`\\remoteComputerName` works when accessed from the Explorer windows app).

**Comment by aza547** [comment] 2022-12-12 21:06
> @mpaland The party's not over :) No needed to fix, use the **cwd** parameter: `glob("**/*.pdf", {cwd:"//host/my_media"}, (err, files) => { if (err) throw err; console.log(files) });`

This works for me, but seems to be far less performant than the initial method (so much so that it's not viable in my application sadly).

**Comment by isaacs** [comment] 2023-02-28 22:12
UNC paths are first class citizens now in v9.  Only took 10 years to fix this bug 😬

**Closed by isaacs** 2023-02-28 22:12 UTC
