### ISSUE TITLE
Glob 7.2.2 broke our jasmine test suites

### ISSUE THREAD

**Issue by AaronSterlingGENEICD** [isaacs/node-glob#474] opened 2022-05-15 06:38 UTC
We reverted to 7.2.0 and everything works fine again. Not sure if this is a jasmine issue or a glob issue, but I figured I should let you know. Please see full writeup here: https://github.com/jasmine/jasmine/issues/1970#issue-1236201037

**Comment by nicolas377** [comment] 2022-05-15 13:22
Duplicate of #471, please see that issue for more details.

**Comment by isaacs** [comment] 2022-05-15 18:32
Should be fixed by glob@7.2.3.  If it isn't, please post a new issue at https://github.com/isaacs/node-glob/issues, ideally with a reproduction case.  Thanks!

**Closed by isaacs** 2022-05-15 18:32 UTC
