### ISSUE TITLE
Inconsistency when run in root drive path `/`, prefixes match with `/`

### ISSUE THREAD

**Issue by reggi** [isaacs/node-glob#584] opened 2024-05-06 14:29 UTC
👋 First off thanks for your work on glob. 🙏

There's a bug in [npm workspaces](https://github.com/npm/cli/issues/7413) that I [tracked back to this unexpected result in glob](https://github.com/npm/cli/issues/7413#issuecomment-2093514472). 

Here's an easy way to demonstrate the issue:

```
➜  Desktop deno eval 'import("npm:glob@10.3.12").then(({ glob }) => glob("bin")).then(console.log)'
[ "bin" ]
➜  Desktop cd /
➜  / deno eval 'import("npm:glob@10.3.12").then(({ glob }) => glob("bin")).then(console.log)'
[ "/bin" ]
```

When run in `~/Desktop` it's matching the folder `bin`, and when run in `/` it's matching `/bin`.

Is this expected behavior?

**Comment by isaacs** [comment] 2024-05-09 13:52
Interesting, so the issue is that an entry in `/` has the `/` prefix attached to it?

That's not expected, no. Definitely a bug, because it's not how bash 5 does it.

**Comment by reggi** [comment] 2024-05-09 14:49
@isaacs yep! thats the issue!

**Comment by isaacs** [comment] 2024-05-09 14:53
Fixed in latest :)

**Closed** 2024-05-09 14:52 UTC
