### ISSUE TITLE
Oh my glob!

### ISSUE THREAD

**Issue by Diokuz** [isaacs/node-glob#399] opened 2019-06-28 15:23 UTC
Why you guys removed an old supercool gif logo? :))

I used glob only because of it)

![image](https://user-images.githubusercontent.com/2929442/60353070-e1fa4280-99d1-11e9-97ed-e9af3d0df612.png)

**Comment by herman-rogers** [comment] 2019-07-11 20:38
I second this. At least slap it in the wiki.

**Comment by lovetingyuan** [comment] 2019-07-12 10:45
![oh-my-glob](https://user-images.githubusercontent.com/7310471/61122733-28bd6180-a4d5-11e9-8a95-b744827252c6.gif)
I like it too.

**Comment by lvl99** [comment] 2019-10-03 16:23
Please bring it back...

**Comment by roccivic** [comment] 2019-10-21 14:51
Duplicate of #396

**Closed** 2019-10-21 17:07 UTC
