### ISSUE TITLE
platform option not works with cwd

### ISSUE THREAD

**Issue by zdm** [isaacs/node-glob#509] opened 2023-03-05 05:03 UTC
On `windows` when `cwm` option is used and `platform` option is set to `linux` - glob returns nothing.

```
const files = glob.globSync( "**/*.js", { cwd: "d:/projects/tmp", platform: "linux" } );
```
I expected that it will return found files with the `linux` path separators.

**Comment by isaacs** [comment] 2023-03-05 16:42
You've said "this is Linux". Then you've passed in a cwd that is not an absolute path (on Linux). So it resolves it to find the absolute cwd, which is {process.cwd()}/d:/etc. And that doesn't exist.

**Comment by isaacs** [comment] 2023-03-05 16:45
Does it work if you use `/projects/tmp` as the cwd, and run it in the d: drive?

**Comment by zdm** [comment] 2023-03-06 05:41
Yes, it works, when `/projects/tmp` is used.
But `d:/projects/tmp` is valid absolute path for windows. 
What os the sense in `platform` option?
I am using platform linux because I need linux path separator in results.

**Comment by isaacs** [comment] 2023-03-06 19:57
The `platform` option is there to tell Glob which platform you're using, for cases when it cannot guess correctly for some reason.  For example, in tests where you may be simulating the file system anyway, and want to verify Windows behavior on a mac or linux machine (or vice versa).

> But d:/projects/tmp is valid absolute path for windows.

Yes, it is, but you've told it you're on linux, so it's not treating that as an absolute path, because it's not an absolute path on linux.

If you use `{platform: 'linux'}`, you're going to be using linux path _resolution_, because you've told it that's what you want.  And `path.posix.resolve('d:/projects/tmp')` is `./d:/projects/tmp`, so that's what you're seeing.  This resolution is required at the start, because the `cwd` parameter might not match the actual process.cwd(), so PathScurry does all filesystem operations with absolute paths.

If you need posix `/` path separators in the results, you can just do `results.map(r => r.replace(/\\/g, '/'))`.

Why do you need `/` path separators on Windows?  I'm open to adding an option to do this, if it's a common enough use case.

**Comment by isaacs** [comment] 2023-03-06 19:59
Closing for now, since this is working as intended.  We can open a new issue if there's a need to add the "use posix path separators on windows" option.

**Closed by isaacs** 2023-03-06 19:59 UTC
