### ISSUE TITLE
UNC Path on Windows 64bit gives empty array

### ISSUE THREAD

**Issue by DilipK01** [isaacs/node-glob#191] opened 2015-04-24 02:10 UTC
I have a bunch of files on a network computer in "sourceDir" folder.
When I use `fs.existsSync(sourceDir + '/myfile1.js')`, it returns true.
In fact, I can also create a subfolder, like, `fs.mkdirSync(path.resolve(sourceDir + '/newSubdir'));`

However, when I use:

``` javascript
glob(sourceDir + '/*.*', { dot: true}, function(err, files) {
   console.log(files); // returns empty array :-(
});
```

I have tried so many different ways without any success, for example,

``` javascript
var sourceDir = '\\\\myserver1.abc.com\\C$\\folder1\\subfolder1';
var sourceDir = '\\myserver1.abc.com\C$\folder1\subfolder1';
var sourceDir = '//myserver1.abc.com/C$/folder1/subfolder1';
```

I have also removed `"C$"` from the above string. (server-name is `"myserver1.abc.com"`).

I'm logged in as local administrator on both the computers. The sourceDir folder has "everyone" full-access right. Both computers have Windows 64-bit. I have the latest version of glob (v5.0.5). 

Nothing works. Can you please help?
Thanks.
Dilip Kumar

**Comment by DilipK01** [comment] 2015-04-24 02:17
Upon submitting this issue I noticed that all my double-backslashes are converted to single-backslashes. For example, four backslashes are converted to two backslashes, and two backslashes are converted to single backslashes. (I might have some typo also) But I think you get the point.

**Comment by isaacs** [comment] 2015-07-14 00:33
In JavaScript, you must always double-up your back-slashes because backslash is the escape character.  So, for example, `a\nx` is the string `{0x61 0x0a 0x78}` (a, LF, x), but `'a\\nx` is the string `{0x61 0x5c 0x6e 0x78}` (a, slash, n, x).

Glob has some difficulties with UNC paths.  (See: https://github.com/isaacs/node-glob/issues/74) so I'm guessing this is a duplicate of #74.

**Comment by isaacs** [comment] 2023-02-28 22:15
No longer an issue in v9.

**Closed by isaacs** 2023-02-28 22:15 UTC
